'use client'

import { motion } from 'framer-motion'

const sections = [
  {
    title: '1. What Are Cookies and Why Do They Matter?',
    content: `A cookie is a small text file that a website places on your device (computer, tablet, or smartphone) when you visit. Cookies allow websites to recognize your device across pages or visits, remember your preferences, measure how you use the site, and deliver certain functionalities.\n\nIn addition to traditional cookies, we use similar technologies including:\n• Web beacons / pixel tags — tiny invisible images embedded in pages or emails that track whether a page was opened or an email was read\n• Local storage and session storage — browser-based data storage that functions similarly to cookies but is stored on your device rather than transmitted to servers\n• JavaScript tracking scripts — code embedded in pages that collects usage data and sends it to analytics platforms\n\nFor simplicity, we refer to all of the above collectively as “cookies” throughout this Policy.\n\nUnderstanding cookies matters because they may involve the collection and processing of your personal data. You have rights and choices regarding this processing, which are explained fully in this document.`
  },
  {
    title: '2. Who Sets Cookies on Our Site?',
    content: `Cookies on our Site are set by two categories of parties:\n\n• **First-party cookies** — set directly by NAYARAi™ for the essential operation and analytics of our Site\n• **Third-party cookies** — set by external service providers whose tools or content are embedded in or linked from our Site. NAYARAi™ does not control third-party cookies. Each third party’s data practices are governed by their own privacy and cookie policies.\n\nThird parties whose cookies may be present on our Site include: Google LLC (Google Analytics), Microsoft Corporation (Microsoft Clarity), Vercel Inc. (hosting infrastructure), Calendly LLC (scheduling widget), LinkedIn Corporation, Meta Platforms Inc. (Facebook/Instagram), X Corp. (Twitter/X), and Pinterest Inc.`
  },
  {
    title: '3. Categories of Cookies We Use',
    items: [
      {
        subtitle: '3.1 Strictly Necessary Cookies',
        content: `These cookies are essential for our Site to function. They cannot be switched off without preventing the Site from operating correctly. They do not collect any information about you for marketing or analytics purposes. They are set either by NAYARAi™ or by our hosting provider (Vercel).\n\nStrictly necessary cookies are always active and do not require your consent under applicable law.`,
        table: {
          headers: ['Cookie Name / Provider', 'Type', 'Purpose', 'Retention', 'Third Party?'],
          rows: [
            ['Session ID cookie', 'Strictly Necessary', 'Maintains your session as you navigate between pages', 'Session (deleted on browser close)', 'No'],
            ['Security / CSRF token', 'Strictly Necessary', 'Prevents cross-site request forgery attacks', 'Session', 'No'],
            ['Load balancing cookie (Vercel)', 'Strictly Necessary', 'Ensures stable performance across Vercel server infrastructure', 'Session', 'Yes — Vercel'],
            ['Cookie consent preference', 'Strictly Necessary', 'Stores your cookie consent choice so you are not asked on every visit', '12 months', 'No']
          ]
        }
      },
      {
        subtitle: '3.2 Analytics and Performance Cookies',
        content: `These cookies help us understand how visitors use our Site — which pages are visited most, how long visitors stay, where they came from, and whether they encounter errors. This data is aggregated and used to improve our Site. These cookies require your consent.\n\n**a) Google Analytics (Google LLC)**\nGoogle Analytics is a web analytics service provided by Google LLC. It uses cookies to collect information about how visitors use our Site. The information generated by the cookie is transmitted to and stored by Google on servers which may be located outside India and the EEA.\n\nNAYARAi has configured Google Analytics with IP anonymization enabled, meaning your IP address is truncated before being used or stored by Google. We do not use Google Analytics to collect personally identifiable information.`,
        table: {
          headers: ['Cookie Name / Provider', 'Type', 'Purpose', 'Retention', 'Third Party?'],
          rows: [
            ['_ga', 'Analytics', 'Registers a unique ID to generate statistical data on how you use the Site', '2 years', 'Yes — Google'],
            ['_ga_[ID]', 'Analytics', 'Used by Google Analytics to persist session state and distinguish between sessions', '2 years', 'Yes — Google'],
            ['_gid', 'Analytics', 'Registers a unique ID to generate statistical data on how you use the Site (session-level)', '24 hours', 'Yes — Google'],
            ['_gat', 'Analytics', 'Used to throttle request rate to Google Analytics servers', '1 minute', 'Yes — Google']
          ]
        },
        extraContent: `Google’s Privacy Policy: https://policies.google.com/privacy | Google Analytics Opt-out: https://tools.google.com/dlpage/gaoptout\n\n**b) Microsoft Clarity (Microsoft Corporation)**\nMicrosoft Clarity is a behavior analytics tool that captures how users interact with our Site through heatmaps and session recordings. It uses cookies and similar technologies to collect interaction data. All data collected by Clarity is processed by Microsoft.`
      },
      {
        subtitle: '', // Continuing 3.2
        content: ``,
        table: {
          headers: ['Cookie Name / Provider', 'Type', 'Purpose', 'Retention', 'Third Party?'],
          rows: [
            ['_clck', 'Analytics', 'Persists the Clarity User ID and preferences to the current site; ties sessions to the same user ID', '1 year', 'Yes — Microsoft'],
            ['_clsk', 'Analytics', 'Connects multiple page views by a user into a single Clarity session recording', '1 day', 'Yes — Microsoft'],
            ['CLID', 'Analytics', 'Identifies the first time Clarity saw this user on any site using Clarity', '1 year', 'Yes — Microsoft'],
            ['ANONCHK', 'Analytics', 'Used to check if logging is enabled for the Clarity service on the bootstrap request', '10 minutes', 'Yes — Microsoft'],
            ['MR', 'Analytics', 'Indicates whether to refresh the MUID (Microsoft User ID)', '7 days', 'Yes — Microsoft'],
            ['MUID', 'Analytics', 'Microsoft User ID — identifies unique web browsers visiting Microsoft sites and services', '1 year', 'Yes — Microsoft'],
            ['SM', 'Analytics', 'Used to synchronize the MUID across Microsoft-owned domains', 'Session', 'Yes — Microsoft']
          ]
        },
        extraContent: `Microsoft’s Privacy Policy: https://privacy.microsoft.com | Clarity Opt-out: https://clarity.microsoft.com/optout\n\n**c) Vercel Analytics (Vercel Inc.)**\nOur Site is hosted on Vercel’s infrastructure. Vercel may collect lightweight performance metrics such as page load times and error rates. This data is generally aggregated and does not identify individual users.`
      },
      {
        subtitle: '', // Continuing 3.2 Vercel table
        content: ``,
        table: {
          headers: ['Cookie Name / Provider', 'Type', 'Purpose', 'Retention', 'Third Party?'],
          rows: [
            ['Vercel performance metrics', 'Analytics / Necessary', 'Infrastructure performance monitoring; ensures Site stability', 'Session', 'Yes — Vercel']
          ]
        }
      },
      {
        subtitle: '3.3 Functional Cookies',
        content: `Functional cookies enable enhanced features and personalization on our Site. They may be set by us or by third-party providers. These cookies do not track your activity on other websites. They require your consent.`,
        table: {
          headers: ['Cookie Name / Provider', 'Type', 'Purpose', 'Retention', 'Third Party?'],
          rows: [
            ['Language / region preference', 'Functional', 'Remembers your selected language or region so you don’t have to reset it on each visit', '12 months', 'No'],
            ['Contact form pre-fill', 'Functional', 'Retains form input data temporarily to improve your experience (if applicable)', 'Session', 'No']
          ]
        }
      },
      {
        subtitle: '3.4 Scheduling Tool Cookies (Calendly)',
        content: `Our Site links to and may embed scheduling widgets from Calendly, LLC (“Calendly”). When you interact with a Calendly scheduling interface, Calendly sets its own cookies on your device. NAYARAi™ does not control these cookies and they are governed solely by Calendly’s Cookie Policy and Privacy Policy.`,
        table: {
          headers: ['Cookie Name / Provider', 'Type', 'Purpose', 'Retention', 'Third Party?'],
          rows: [
            ['__cf_bm (Cloudflare)', 'Necessary / Functional', 'Bot management and security cookie used by Calendly’s CDN provider (Cloudflare)', '30 minutes', 'Yes — Calendly / Cloudflare'],
            ['calendly.* cookies', 'Functional / Analytics', 'Session management, preference storage, and usage analytics for the Calendly scheduling interface', 'Varies (session to 1 year)', 'Yes — Calendly']
          ]
        },
        extraContent: `Calendly’s Privacy Policy: https://calendly.com/pages/privacy`
      },
      {
        subtitle: '3.5 Social Media and Third-Party Platform Cookies',
        content: `Our Site displays icons and links to social media and third-party platforms including LinkedIn, YouTube, X (formerly Twitter), Facebook, Instagram, and Pinterest. If you are logged into any of these platforms in the same browser session, those platforms may set tracking cookies on our Site pages, particularly if we embed any of their content (such as a LinkedIn follow button or a YouTube video).\n\nNAYARAi does not control any cookies set by these third-party platforms. Their presence and behavior depend on your interaction with those platforms and their own cookie policies. We strongly recommend reviewing each platform’s cookie policy:\n\n• YouTube / Google: https://policies.google.com/privacy\n• LinkedIn: https://www.linkedin.com/legal/cookie-policy\n• X (Twitter): https://x.com/en/privacy\n• Facebook / Meta: https://www.facebook.com/privacy/policy\n• Instagram / Meta: https://privacycenter.instagram.com/policy\n• Pinterest: https://policy.pinterest.com/en/cookies\n\nThe display of third-party logos on our Site is solely for identification and navigation purposes. Clicking on these icons will take you to the respective third-party platforms, where you will be subject to their own terms and cookie practices.`
      },
      {
        subtitle: '3.6 Marketing and Advertising Cookies',
        content: `NAYARAi™ currently does not operate paid advertising campaigns or use retargeting or behavioral advertising cookies on our Site. We do not use cookies to track your activity across other websites for advertising purposes.\n\nIf this changes in the future, we will update this Cookie Policy, refresh our cookie consent mechanism, and seek your explicit consent before activating any marketing cookies.`
      }
    ]
  },
  {
    title: '4. Cookie Consent and Your Choices',
    items: [
      {
        subtitle: '4.1 How We Obtain Your Consent',
        content: `When you first visit our Site, a cookie consent banner will be displayed. This banner allows you to:\n• Accept all cookies (including analytics and functional cookies)\n• Reject non-essential cookies (only strictly necessary cookies will be set)\n• Manage your preferences in detail via the Cookie Settings panel\n\nStrictly necessary cookies are activated by default as they are essential for the Site to function. All other cookies are only activated with your explicit consent.`
      },
      {
        subtitle: '4.2 Withdrawing or Changing Consent',
        content: `You can withdraw or adjust your cookie consent at any time using the following methods:\n• Cookie Settings panel — accessible via the “Cookie Settings” link in the footer of our Site\n• Browser settings — you can configure your browser to refuse, delete, or notify you about cookies (see Section 5 below)\n• Third-party opt-out tools — for specific providers such as Google Analytics (see Section 5.2)\n\nPlease note that withdrawing consent does not affect the lawfulness of processing that occurred before withdrawal. It also means that certain features of the Site may not function as intended.`
      }
    ]
  },
  {
    title: '5. How to Manage and Disable Cookies',
    items: [
      {
        subtitle: '5.1 Browser-Level Cookie Controls',
        content: `All major browsers allow you to control cookies through their settings. The steps vary by browser. Below are links to instructions for the most common browsers:\n\n• Google Chrome: Settings > Privacy and Security > Cookies and other site data\n• Mozilla Firefox: Settings > Privacy & Security > Cookies and Site Data\n• Safari (macOS/iOS): Preferences / Settings > Privacy > Manage Website Data\n• Microsoft Edge: Settings > Cookies and site permissions\n• Opera: Settings > Advanced > Privacy & Security > Cookies\n\nPlease be aware that blocking or deleting all cookies, including strictly necessary cookies, may prevent our Site from functioning correctly and may limit your ability to use certain features.`
      },
      {
        subtitle: '5.2 Third-Party Analytics Opt-Outs',
        content: `You can opt out of specific third-party analytics tools using the following official opt-out mechanisms:\n\n• Google Analytics: Install the Google Analytics Opt-out Browser Add-on at https://tools.google.com/dlpage/gaoptout\n• Google personalized advertising: Manage preferences at https://adssettings.google.com\n• Microsoft Clarity: opt out at https://clarity.microsoft.com/optout\n• Microsoft advertising: Manage preferences at https://account.microsoft.com/privacy\n\nUsing these opt-out mechanisms prevents the relevant provider from collecting data about your visits from that point forward. Existing data already collected is subject to the third party’s own retention and deletion policies.`
      },
      {
        subtitle: '5.3 Do Not Track Signals',
        content: `Some browsers transmit a “Do Not Track” (DNT) signal to websites. At present, there is no industry-wide standard for how websites should respond to DNT signals. Our Site does not currently respond to DNT signals in a standardized way. We continue to monitor developments in this area and will update this Policy if a standardized approach is adopted.`
      }
    ]
  },
  {
    title: '6. Cookie Retention Periods — Summary',
    content: `Different cookies are retained for different lengths of time depending on their purpose:`,
    table: {
      headers: ['Cookie Name / Provider', 'Type', 'Purpose', 'Retention', 'Third Party?'],
      rows: [
        ['Session cookies', 'Strictly Necessary', 'Deleted when you close your browser', '—', 'Varies'],
        ['Cookie consent preference', 'Necessary', 'Stores your consent decision', '12 months', 'No'],
        ['Google Analytics (_ga)', 'Analytics', 'Tracks unique visitors', '2 years', 'Yes — Google'],
        ['Google Analytics (_gid)', 'Analytics', 'Session-level tracking', '24 hours', 'Yes — Google'],
        ['Microsoft Clarity (_clck)', 'Analytics', 'User identification for Clarity', '1 year', 'Yes — Microsoft'],
        ['Microsoft Clarity (MUID)', 'Analytics', 'Microsoft User ID', '1 year', 'Yes — Microsoft'],
        ['Calendly cookies', 'Functional', 'Scheduling session management', 'Session to 1 year', 'Yes — Calendly'],
        ['Functional / preference cookies', 'Functional', 'User preferences and personalization', 'Up to 12 months', 'No']
      ]
    },
    extraContent: `We periodically audit the cookies in use on our Site and update this table to reflect current practice. Third-party cookie retention periods are set by those third parties and may change without notice.`
  },
  {
    title: '7. International Data Transfers via Cookies',
    content: `Some cookies set by third parties (particularly Google Analytics and Microsoft Clarity) involve the transfer of data to servers located outside India, including within the United States and the European Union. Such transfers are subject to the data protection policies of the respective third parties and applicable international data transfer frameworks.\n\nNAYARAi has configured Google Analytics with IP anonymization to minimize the amount of personal data transferred. However, NAYARAi™ does not control the data transfer practices of other third-party cookie providers. We encourage you to review their privacy policies.`
  },
  {
    title: '8. Cookies and Children',
    content: `Our Site is intended for business professionals and is not directed at individuals under the age of 18. We do not knowingly use cookies to collect data from minors. If you are under 18, please do not use our Site or allow cookies to be set on your device through our Site.`
  },
  {
    title: '9. Updates to This Cookie Policy',
    content: `We may update this Cookie Policy from time to time to reflect changes in the cookies we use, the services we offer, changes in third-party practices, or changes in applicable law. When we make material changes, we will:\n• Update the effective date at the top of this Policy\n• Post the revised Policy on our Site\n• Refresh the cookie consent banner so that you can review and reconfirm your preferences\n\nWe encourage you to review this Policy periodically to stay informed about how we use cookies.`
  },
  {
    title: '10. Contact Us — Cookie Enquiries',
    content: `If you have any questions or concerns about our use of cookies or this Cookie Policy, please contact us:\n\n**Organization:** NAYARAi™ — Data Privacy Team\n**Email:** info@nayarai.com\n**Phone:** +91 (789) 265 7083\n**Address:** Bangalore, Karnataka, India\n**Website:** nayarai.com\n\nWe will respond to all cookie-related enquiries within 30 days.`
  }
]

export default function CookiePolicyPage() {
  const renderText = (text: string) => {
    return text.split('\n').map((paragraph, i) => {
      const parts = paragraph.split(/\*\*(.*?)\*\*/g);
      return (
        <p key={i}>
          {parts.map((p, j) => j % 2 === 1 ? <strong key={j} className="text-foreground">{p}</strong> : p)}
        </p>
      );
    });
  };

  const renderTable = (table: any) => {
    return (
      <div className="overflow-x-auto my-6 border border-border/50 rounded-xl">
        <table className="w-full text-sm text-left">
          <thead className="bg-secondary/50 text-foreground font-semibold border-b border-border/50">
            <tr>
              {table.headers.map((header: string, i: number) => (
                <th key={i} className="px-4 py-3 border-r border-border/50 last:border-r-0 whitespace-nowrap">
                  {header}
                </th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-border/50 text-muted-foreground">
            {table.rows.map((row: string[], i: number) => (
              <tr key={i} className="hover:bg-secondary/20 transition-colors">
                {row.map((cell: string, j: number) => (
                  <td key={j} className="px-4 py-3 border-r border-border/50 last:border-r-0">
                    {cell}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    );
  };

  return (
    <div className="relative min-h-screen">
      {/* Hero Section */}
      <section className="pt-40 pb-12 px-6 relative overflow-hidden">
        <motion.div
          animate={{
            scale: [1, 1.3, 1],
            opacity: [0.3, 0.5, 0.3],
          }}
          transition={{
            duration: 8,
            repeat: Number.POSITIVE_INFINITY,
            ease: "easeInOut"
          }}
          className="absolute top-0 right-0 w-96 h-96 rounded-full bg-accent/20 blur-3xl pointer-events-none"
        />

        <div className="max-w-4xl mx-auto relative z-10">
          <motion.div
             initial={{ opacity: 0, y: 30 }}
             animate={{ opacity: 1, y: 0 }}
             transition={{ duration: 1, ease: [0.22, 1, 0.36, 1] }}
             className="text-center md:text-left mb-16"
          >
            <h1 className="font-display text-5xl md:text-6xl lg:text-7xl font-bold mb-6 text-balance uppercase">
              {'COOKIE '}
              <span className="text-accent">{'POLICY'}</span>
            </h1>
            <p className="text-xl text-muted-foreground mb-2">Effective Date: April 14, 2026<span className="mx-4">|</span>Version: 2.0</p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="mb-12 text-center md:text-left"
          >
            <p className="text-lg md:text-xl leading-relaxed text-muted-foreground">
              This Cookie Policy explains in explicit detail what cookies and tracking technologies NAYARAi™ uses on nayarai.com, why we use them, what data they collect, how long they are retained, and how you can control or opt out of them. We are committed to full transparency about our use of tracking technologies.
            </p>
          </motion.div>
        </div>
      </section>

      {/* Content Sections */}
      <section className="pb-32 px-6">
        <div className="max-w-4xl mx-auto space-y-16">
          {sections.map((section, idx) => (
            <motion.div 
              key={idx}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: idx * 0.05 }}
              className="space-y-8"
            >
              <h2 className="font-display text-2xl md:text-3xl font-bold text-foreground border-b border-border/50 pb-4">
                {section.title}
              </h2>
              
              {section.content && (
                <div className="text-muted-foreground leading-relaxed whitespace-pre-line text-justify space-y-4">
                  {renderText(section.content)}
                </div>
              )}

              {section.table && renderTable(section.table)}

              {section.extraContent && (
                <div className="text-muted-foreground leading-relaxed whitespace-pre-line text-justify space-y-4">
                  {renderText(section.extraContent)}
                </div>
              )}

              {section.items && (
                <div className="space-y-10">
                  {section.items.map((item, itemIdx) => (
                    <div key={itemIdx} className="space-y-4">
                      {item.subtitle && (
                        <h3 className="font-display text-xl font-semibold text-foreground">
                          {item.subtitle}
                        </h3>
                      )}
                      
                      {item.content && (
                        <div className="text-muted-foreground leading-relaxed whitespace-pre-line text-justify space-y-4">
                          {renderText(item.content)}
                        </div>
                      )}

                      {item.table && renderTable(item.table)}

                      {item.extraContent && (
                        <div className="text-muted-foreground leading-relaxed whitespace-pre-line text-justify space-y-4">
                          {renderText(item.extraContent)}
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </motion.div>
          ))}
        </div>
      </section>
    </div>
  )
}
